# configuration.nix
# This is the main NixOS configuration file that imports all modules.
# It sets up the basic system configuration and aggregates functionality from modules.
# Do not edit this file directly for major changes; use modules instead.
# Generated based on the architecture description for NixOS All-in-One family server.

{ config, pkgs, lib, ... }:

{
  imports = [
    # Import all modules as per architecture
    ./modules/base.nix      # Base services: SSH, Cockpit, Fail2Ban, Prometheus, Grafana
    ./modules/nftables.nix  # Network: nftables, VLAN, TProxy
    ./modules/btrfs.nix     # Storage: BTRFS, snapshots, shares, backups
    ./modules/containers.nix # Containers: Podman definitions for 60+ services
    ./modules/permissions.nix # Permissions: Git, sops, immutable, auditd
  ];

  # Basic system settings
  boot.loader = {
    systemd-boot.enable = true;  # Use systemd-boot for EFI
    efi.canTouchEfiVariables = true;
  };

  # Kernel and supported filesystems
  boot.supportedFilesystems = [ "btrfs" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;  # Use latest kernel (6.x)

  # Networking basics (detailed in nftables.nix)
  networking.hostName = "nixos";  # Hostname as per flake
  networking.useDHCP = false;  # Managed by systemd-networkd in modules

  # Time zone and locale
  time.timeZone = "Asia/Shanghai";  # Assumed; adjust as needed
  i18n.defaultLocale = "en_US.UTF-8";

  # System packages (essentials)
  environment.systemPackages = with pkgs; [
    vim  # Basic editor
    git  # For permissions module
    curl  # For scripts
    rsync  # For backups
    lm-sensors  # Hardware monitoring
  ];

  # Enable Podman for containers
  virtualisation.podman = {
    enable = true;
    dockerCompat = true;  # Optional Docker compatibility
    defaultNetwork.settings.dns_enabled = true;
  };

  # Sops-nix configuration (secrets management)
  sops = {
    defaultSopsFile = ./secrets.yaml;  # Encrypted secrets file
    age.keyFile = "/var/lib/sops-nix/key.txt";  # Adjust path as needed
  };

  # Users (basic admin user; add your own)
  users.users.root = {
    openssh.authorizedKeys.keys = [ ];  # Add your SSH keys via sops if needed
  };
  users.users.admin = {  # Example admin user
    isNormalUser = true;
    extraGroups = [ "wheel" "podman" "data" ];  # sudo, containers, storage access
    openssh.authorizedKeys.keys = [ ];  # Secure via sops
  };

  # Security hardening
  security.sudo.wheelNeedsPassword = false;  # Optional; require password for production
  security.auditd.enable = true;  # Enabled in permissions.nix

  # System version
  system.stateVersion = "25.11";  # Match NixOS version

  # Allow unfree packages if needed (e.g., for some containers)
  nixpkgs.config.allowUnfree = true;

  # Auto-upgrade (optional; ties into Git in permissions)
  system.autoUpgrade = {
    enable = true;
    flake = "path:/etc/nixos";  # Assumes Git repo
    flags = [ "--update-input" "nixpkgs" ];
  };
}
